#!/bin/bash
# ────────────────────────────────────────────────────────────────────────
# Post-provision hook: Write .env file from azd environment outputs.
# ────────────────────────────────────────────────────────────────────────

set -euo pipefail

echo "📝 Writing .env from azd environment..."

cat > .env << EOF
# Generated by azd post-provision hook — $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Entra ID
ENTRA_CLIENT_ID=$(azd env get-value ENTRA_CLIENT_ID 2>/dev/null || echo "")
ENTRA_CLIENT_SECRET=$(azd env get-value ENTRA_CLIENT_SECRET 2>/dev/null || echo "")
ENTRA_TENANT_ID=$(azd env get-value ENTRA_TENANT_ID 2>/dev/null || echo "")

# Cosmos DB
AZURE_COSMOSDB_ENDPOINT=$(azd env get-value AZURE_COSMOSDB_ENDPOINT 2>/dev/null || echo "")
AZURE_COSMOSDB_DATABASE=$(azd env get-value AZURE_COSMOSDB_DATABASE 2>/dev/null || echo "todo-database")
AZURE_COSMOSDB_CONTAINER=todos
AZURE_COSMOSDB_OAUTH_CONTAINER=oauth-clients

# Server
MCP_SERVER_BASE_URL=$(azd env get-value MCP_SERVER_BASE_URL 2>/dev/null || echo "http://localhost:8000")
PORT=8000
RUNNING_IN_PRODUCTION=false
EOF

echo "✅ .env file written"
