# Post-provision hook: Write .env file (Windows)

$ErrorActionPreference = "Stop"

$envContent = @"
# Generated by azd post-provision hook — $(Get-Date -Format o)

# Entra ID
ENTRA_CLIENT_ID=$(azd env get-value ENTRA_CLIENT_ID 2>$null)
ENTRA_CLIENT_SECRET=$(azd env get-value ENTRA_CLIENT_SECRET 2>$null)
ENTRA_TENANT_ID=$(azd env get-value ENTRA_TENANT_ID 2>$null)

# Cosmos DB
AZURE_COSMOSDB_ENDPOINT=$(azd env get-value AZURE_COSMOSDB_ENDPOINT 2>$null)
AZURE_COSMOSDB_DATABASE=$(azd env get-value AZURE_COSMOSDB_DATABASE 2>$null)
AZURE_COSMOSDB_CONTAINER=todos
AZURE_COSMOSDB_OAUTH_CONTAINER=oauth-clients

# Server
MCP_SERVER_BASE_URL=$(azd env get-value MCP_SERVER_BASE_URL 2>$null)
PORT=8000
RUNNING_IN_PRODUCTION=false
"@

$envContent | Out-File -FilePath ".env" -Encoding utf8
Write-Host "✅ .env file written"
